"""
Spaced Repetition SAT/GRE Vocabulary Workbook Generator
Produces a 110-page, 6x9-inch KDP-ready PDF using ReportLab.
Run:  python generate_workbook.py
"""

import re
import random

from reportlab.lib.pagesizes import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from reportlab.lib.colors import black, white, HexColor
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak, Flowable,
)
from reportlab.lib.units import inch as IN

# ── Page geometry ──────────────────────────────────────────────────────────────
PAGE_W   = 6   * IN
PAGE_H   = 9   * IN
GUTTER   = 0.85 * IN   # inside / left margin (KDP gutter)
OUTER    = 0.6  * IN   # outside / right margin
TOP      = 0.6  * IN
BOTTOM   = 0.6  * IN
BODY_W   = PAGE_W - GUTTER - OUTER   # ≈ 4.55 in

# ── Word dataset: 525 entries ─────────────────────────────────────────────────
# Format: (word, part-of-speech, short definition, contextual example sentence)
WORDS = [
    ("Abate",        "v.",   "To reduce in intensity",
     "The storm began to abate as evening arrived."),
    ("Aberrant",     "adj.", "Deviating from the normal",
     "His aberrant behavior alarmed his colleagues."),
    ("Abeyance",     "n.",   "Temporary suspension",
     "The project was held in abeyance pending funding."),
    ("Abjure",       "v.",   "To solemnly renounce",
     "She abjured her former political affiliations."),
    ("Abscond",      "v.",   "To flee to escape consequences",
     "The treasurer absconded with the company funds."),
    ("Abstemious",   "adj.", "Restrained in eating and drinking",
     "His abstemious lifestyle contributed to his longevity."),
    ("Abstruse",     "adj.", "Difficult to understand",
     "The lecture was too abstruse for the freshmen."),
    ("Accede",       "v.",   "To agree or give consent",
     "The manager acceded to the team's request."),
    ("Acerbic",      "adj.", "Sharp and harsh in tone",
     "Her acerbic wit often made adversaries uncomfortable."),
    ("Acrimony",     "n.",   "Bitterness or ill feeling",
     "The divorce was marked by great acrimony."),
    ("Acumen",       "n.",   "Ability to make good judgments quickly",
     "Her business acumen set her apart from peers."),
    ("Admonish",     "v.",   "To warn or reprimand firmly",
     "The teacher admonished students for their tardiness."),
    ("Adroit",       "adj.", "Clever or skillful in using the mind",
     "She was adroit at navigating difficult situations."),
    ("Adulterate",   "v.",   "To make impure by adding inferior matter",
     "The supplier adulterated the product to cut costs."),
    ("Affable",      "adj.", "Friendly and easy to talk to",
     "The affable host made everyone feel welcome."),
    ("Aggrandize",   "v.",   "To increase power or importance of",
     "He used the role to aggrandize his own standing."),
    ("Alacrity",     "n.",   "Brisk and cheerful readiness",
     "She accepted the challenge with surprising alacrity."),
    ("Allay",        "v.",   "To diminish or put to rest fear",
     "The doctor's words did little to allay his anxiety."),
    ("Aloof",        "adj.", "Cool and distant; not forthcoming",
     "The new employee seemed aloof during orientation."),
    ("Altruism",     "n.",   "Selfless concern for others",
     "Her altruism was evident in decades of volunteer work."),
    ("Amalgamate",   "v.",   "To combine into one whole",
     "The two firms decided to amalgamate operations."),
    ("Ambiguous",    "adj.", "Open to more than one interpretation",
     "The contract contained several ambiguous clauses."),
    ("Ambivalent",   "adj.", "Having mixed feelings about something",
     "He felt ambivalent about moving to a new city."),
    ("Ameliorate",   "v.",   "To make something bad better",
     "New policies ameliorated working conditions."),
    ("Anachronism",  "n.",   "Something out of its proper time",
     "Using a quill today would be a charming anachronism."),
    ("Analogous",    "adj.", "Comparable in certain respects",
     "The brain is analogous to a computer."),
    ("Anodyne",      "adj.", "Not likely to cause offence; bland",
     "The politician gave an anodyne response."),
    ("Anomalous",    "adj.", "Deviating from what is expected",
     "The anomalous results prompted a repeat study."),
    ("Antagonize",   "v.",   "To cause someone to become hostile",
     "His comments only served to antagonize the opposition."),
    ("Antiquated",   "adj.", "Old-fashioned or outdated",
     "The firm still used antiquated accounting methods."),
    ("Apathy",       "n.",   "Lack of interest or concern",
     "Voter apathy was blamed for the low turnout."),
    ("Appease",      "v.",   "To pacify by making concessions",
     "The treaty was designed to appease the kingdom."),
    ("Approbation",  "n.",   "Approval or praise",
     "The novel met with widespread approbation."),
    ("Archaic",      "adj.", "Very old or old-fashioned",
     "The text was filled with archaic vocabulary."),
    ("Arduous",      "adj.", "Involving a lot of effort; difficult",
     "The climb to the summit was arduous but rewarding."),
    ("Articulate",   "adj.", "Able to speak fluently and coherently",
     "She was an articulate spokesperson."),
    ("Ascertain",    "v.",   "To find out for certain",
     "Investigators tried to ascertain the cause."),
    ("Ascetic",      "adj.", "Characterized by severe self-discipline",
     "The monk lived an ascetic life of prayer."),
    ("Assiduous",    "adj.", "Showing great care and perseverance",
     "Her assiduous preparation paid off on the exam."),
    ("Assuage",      "v.",   "To make an unpleasant feeling less intense",
     "He tried to assuage her grief with kind words."),
    ("Astute",       "adj.", "Able to assess situations accurately",
     "The astute investor avoided the market crash."),
    ("Atrophy",      "v.",   "To gradually decline in effectiveness",
     "His skills began to atrophy without regular practice."),
    ("Attenuate",    "v.",   "To reduce in force or effect",
     "Distance attenuated the sound of the explosion."),
    ("Audacious",    "adj.", "Showing willingness to take bold risks",
     "The startup's audacious plan captured investors."),
    ("Austere",      "adj.", "Severe; without luxury",
     "The austere décor reflected minimalist tastes."),
    ("Avarice",      "n.",   "Extreme greed for wealth",
     "Avarice drove him to betray his closest allies."),
    ("Avid",         "adj.", "Having keen interest in something",
     "She was an avid reader of historical fiction."),
    ("Axiom",        "n.",   "A statement regarded as obviously true",
     "Supply and demand is an economic axiom."),
    ("Banal",        "adj.", "Lacking originality; obvious",
     "The film's dialogue was predictable and banal."),
    ("Belabor",      "v.",   "To elaborate a point excessively",
     "He tended to belabor his points in every meeting."),
    ("Bellicose",    "adj.", "Aggressive; willing to fight",
     "The bellicose rhetoric raised international tensions."),
    ("Benign",       "adj.", "Gentle and kindly; not harmful",
     "The doctor confirmed the tumor was benign."),
    ("Beseech",      "v.",   "To ask someone urgently and fervently",
     "She beseeched the council to reconsider."),
    ("Blandish",     "v.",   "To coax with flattery",
     "He tried to blandish the editor into publishing."),
    ("Blight",       "n.",   "Something that spoils or damages",
     "Corruption was a blight on the city's reputation."),
    ("Bombastic",    "adj.", "High-sounding but with little substance",
     "His bombastic speech impressed few."),
    ("Boorish",      "adj.", "Rough and bad-mannered",
     "His boorish conduct at dinner embarrassed his hosts."),
    ("Brazen",       "adj.", "Bold and without shame",
     "The brazen theft was captured on cameras."),
    ("Brevity",      "n.",   "Concise and exact use of words",
     "Good writing is distinguished by its brevity."),
    ("Bucolic",      "adj.", "Relating to pleasant aspects of countryside",
     "They spent a bucolic afternoon in the meadows."),
    ("Burgeon",      "v.",   "To begin to grow or increase rapidly",
     "The city's tech sector began to burgeon."),
    ("Cacophony",    "n.",   "A harsh discordant mixture of sounds",
     "The construction site was a cacophony of noise."),
    ("Callous",      "adj.", "Showing insensitive disregard for others",
     "His callous dismissal of concerns shocked everyone."),
    ("Candor",       "n.",   "The quality of being open and honest",
     "She appreciated his candor during the discussion."),
    ("Capricious",   "adj.", "Given to sudden unaccountable changes",
     "The capricious weather made planning difficult."),
    ("Castigate",    "v.",   "To reprimand someone severely",
     "The critic castigated the author for careless errors."),
    ("Caustic",      "adj.", "Sarcastic in a scathing way",
     "Her caustic remarks stung more than she intended."),
    ("Censure",      "v.",   "To express severe disapproval of",
     "The committee voted to censure the senator."),
    ("Chicanery",    "n.",   "The use of trickery to achieve aims",
     "The trial exposed years of legal chicanery."),
    ("Circuitous",   "adj.", "Longer than the most direct way",
     "He took a circuitous route to avoid traffic."),
    ("Clandestine",  "adj.", "Done in secret",
     "They held clandestine meetings in the warehouse."),
    ("Clemency",     "n.",   "Mercy and leniency toward offenders",
     "The governor granted clemency to several prisoners."),
    ("Coalesce",     "v.",   "To come together to form one whole",
     "Disparate factions coalesced into a movement."),
    ("Cogent",       "adj.", "Clear, logical, and convincing",
     "She presented a cogent argument for reform."),
    ("Complacent",   "adj.", "Showing uncritical satisfaction",
     "The team grew complacent after early victories."),
    ("Conciliatory", "adj.", "Intended to lessen hostility",
     "His conciliatory tone helped ease the tension."),
    ("Condone",      "v.",   "To accept or allow behavior that is wrong",
     "The school does not condone bullying."),
    ("Confound",     "v.",   "To cause surprise or confusion in",
     "The unexpected results confounded researchers."),
    ("Convoluted",   "adj.", "Extremely complex and difficult to follow",
     "The instructions were so convoluted no one followed them."),
    ("Copious",      "adj.", "Abundant in supply or quantity",
     "She took copious notes throughout the lecture."),
    ("Corroborate",  "v.",   "To confirm or give support to a statement",
     "The testimony corroborated the defendant's alibi."),
    ("Credulity",    "n.",   "Tendency to believe things too readily",
     "Advertisers exploit the credulity of young consumers."),
    ("Culpable",     "adj.", "Deserving blame or censure",
     "The manager was found culpable for the losses."),
    ("Cursory",      "adj.", "Hasty and not thorough",
     "A cursory glance revealed obvious errors."),
    ("Cynicism",     "n.",   "Belief that people are self-interested",
     "Years of disappointment bred cynicism in the journalist."),
    ("Daunt",        "v.",   "To make someone feel intimidated",
     "The scale of the project daunted even veterans."),
    ("Debacle",      "n.",   "A sudden disaster or complete failure",
     "The product launch turned into a public debacle."),
    ("Decorum",      "n.",   "Behavior in keeping with good taste",
     "The ceremony was conducted with appropriate decorum."),
    ("Deference",    "n.",   "Humble submission and respect",
     "She spoke with deference to the senior professor."),
    ("Deft",         "adj.", "Neatly skillful and quick in movement",
     "With a deft motion, she caught the falling glass."),
    ("Delineate",    "v.",   "To describe or portray precisely",
     "The report delineated the steps needed for reform."),
    ("Demagogue",    "n.",   "A leader who exploits popular desires",
     "History is littered with demagogues who exploited fear."),
    ("Denounce",     "v.",   "To publicly declare wrong or evil",
     "World leaders denounced the act of terrorism."),
    ("Deprecate",    "v.",   "To express disapproval of",
     "He deprecated the use of violence."),
    ("Deride",       "v.",   "To express contempt for; to ridicule",
     "Critics derided the film as shallow."),
    ("Desultory",    "adj.", "Lacking a plan; going randomly",
     "He made desultory attempts to learn the language."),
    ("Deter",        "v.",   "To discourage from acting",
     "Strict penalties are meant to deter drunk driving."),
    ("Didactic",     "adj.", "Intended to teach, especially morally",
     "The novel was overly didactic and lost readers."),
    ("Diffident",    "adj.", "Modest due to lack of self-confidence",
     "The diffident student rarely raised her hand."),
    ("Digress",      "v.",   "To leave the main subject temporarily",
     "He digressed so often that his point was lost."),
    ("Dilettante",   "n.",   "A person who dabbles superficially",
     "He was a dilettante who mastered none of his arts."),
    ("Diligent",     "adj.", "Having careful and persistent effort",
     "Her diligent research produced a groundbreaking thesis."),
    ("Disabuse",     "v.",   "To persuade that an idea is mistaken",
     "The mentor tried to disabuse him of false expectations."),
    ("Discern",      "v.",   "To recognize or find out",
     "It was difficult to discern his true intentions."),
    ("Disdain",      "n.",   "Feeling that someone is unworthy",
     "She regarded his comments with barely concealed disdain."),
    ("Disparate",    "adj.", "Essentially different; not comparable",
     "The committee brought together disparate viewpoints."),
    ("Dispassionate","adj.", "Not influenced by strong emotion",
     "The judge offered a dispassionate analysis."),
    ("Dissemble",    "v.",   "To conceal true motives by pretense",
     "He dissembled his anxiety behind a confident smile."),
    ("Dissonance",   "n.",   "Lack of harmony or agreement",
     "There was cognitive dissonance in his contradictory beliefs."),
    ("Diverge",      "v.",   "To develop in different directions",
     "Their opinions diverged sharply on fiscal policy."),
    ("Divulge",      "v.",   "To make known private information",
     "He refused to divulge the source of his information."),
    ("Dogmatic",     "adj.", "Laying down principles as unquestionable",
     "Her dogmatic approach stifled creative discussion."),
    ("Duplicity",    "n.",   "Deceitfulness; double-dealing",
     "The spy's duplicity was eventually uncovered."),
    ("Ebullient",    "adj.", "Cheerful and full of energy",
     "Her ebullient personality lit up every room."),
    ("Eccentric",    "adj.", "Unconventional and slightly strange",
     "The eccentric inventor lived alone with machines."),
    ("Efficacy",     "n.",   "The ability to produce a desired result",
     "Clinical trials confirmed the drug's efficacy."),
    ("Effrontery",   "n.",   "Insolent or impertinent behavior",
     "He had the effrontery to demand a promotion after a week."),
    ("Egregious",    "adj.", "Outstandingly bad; shocking",
     "The report documented egregious rights violations."),
    ("Elegy",        "n.",   "A mournful poem, especially for the dead",
     "He wrote an elegy for his late mentor."),
    ("Elicit",       "v.",   "To evoke or draw out a response",
     "The teacher asked probing questions to elicit discussion."),
    ("Embroil",      "v.",   "To involve deeply in conflict",
     "The scandal embroiled the minister in controversy."),
    ("Empirical",    "adj.", "Based on observation or experience",
     "The team sought empirical evidence for the hypothesis."),
    ("Enervate",     "v.",   "To weaken or drain of energy",
     "The relentless heat enervated the hikers."),
    ("Enigmatic",    "adj.", "Difficult to interpret; mysterious",
     "The Mona Lisa's enigmatic smile has puzzled viewers for centuries."),
    ("Ephemeral",    "adj.", "Lasting for a very short time",
     "Social media fame is often ephemeral."),
    ("Equivocal",    "adj.", "Open to more than one interpretation",
     "His equivocal answer left us no clearer than before."),
    ("Equivocate",   "v.",   "To use ambiguous language to conceal truth",
     "The politician equivocated rather than answering directly."),
    ("Erudite",      "adj.", "Having great knowledge or learning",
     "The erudite professor could speak to any topic."),
    ("Esoteric",     "adj.", "Understood by only a small group",
     "His interests were esoteric and few could share them."),
    ("Euphemism",    "n.",   "A mild word substituted for an offensive one",
     "'Passed away' is a euphemism for 'died.'"),
    ("Evanescent",   "adj.", "Soon passing out of sight or memory",
     "Youth is evanescent, and must be treasured."),
    ("Exacerbate",   "v.",   "To make a problem worse",
     "Lack of sleep can exacerbate feelings of anxiety."),
    ("Exculpate",    "v.",   "To show someone is not guilty",
     "New evidence emerged to exculpate the wrongly convicted."),
    ("Exigent",      "adj.", "Pressing; requiring immediate action",
     "The crisis created exigent circumstances for the team."),
    ("Exonerate",    "v.",   "To officially absolve from blame",
     "The DNA evidence exonerated the accused."),
    ("Expedient",    "adj.", "Convenient but possibly unprincipled",
     "The expedient solution was not necessarily the right one."),
    ("Extol",        "v.",   "To praise enthusiastically",
     "The press extolled the athlete's remarkable discipline."),
    ("Extraneous",   "adj.", "Irrelevant or unrelated to the subject",
     "The editor removed all extraneous detail."),
    ("Facetious",    "adj.", "Treating serious issues with humor",
     "His facetious comment during the eulogy offended many."),
    ("Fallacious",   "adj.", "Based on a mistaken belief; misleading",
     "The argument was built on a fallacious premise."),
    ("Fatuous",      "adj.", "Silly and pointless",
     "He made a fatuous suggestion that everyone ignored."),
    ("Fawn",         "v.",   "To give servile flattery; to seek favor",
     "Courtiers fawned over the monarch at every opportunity."),
    ("Feckless",     "adj.", "Lacking initiative or strong character",
     "The feckless manager let the department drift."),
    ("Fecund",       "adj.", "Producing many offspring; highly productive",
     "The fecund novelist published six books in three years."),
    ("Fervent",      "adj.", "Having passionate intensity",
     "She was a fervent advocate for animal rights."),
    ("Filibuster",   "n.",   "An action that delays legislation",
     "The senator staged a filibuster to stall the vote."),
    ("Flippant",     "adj.", "Not showing a serious attitude",
     "His flippant reply angered the grieving family."),
    ("Foment",       "v.",   "To instigate or stir up trouble",
     "Agitators tried to foment unrest in the city."),
    ("Forestall",    "v.",   "To prevent by taking advance action",
     "Early intervention can forestall many health problems."),
    ("Fortuitous",   "adj.", "Happening by lucky chance",
     "A fortuitous meeting at a conference launched his career."),
    ("Fractious",    "adj.", "Irritable; quarrelsome",
     "The fractious committee failed to reach agreement."),
    ("Furtive",      "adj.", "Attempting to avoid notice",
     "He cast a furtive glance over his shoulder."),
    ("Garrulous",    "adj.", "Excessively talkative",
     "The garrulous neighbor kept him at the door for an hour."),
    ("Glib",         "adj.", "Fluent but insincere and shallow",
     "His glib assurances failed to reassure investors."),
    ("Grandiloquent","adj.", "Using pompous or extravagant language",
     "His grandiloquent speech masked a shallow argument."),
    ("Gratuitous",   "adj.", "Uncalled for; lacking good reason",
     "The film was criticized for its gratuitous violence."),
    ("Gregarious",   "adj.", "Fond of company; sociable",
     "Her gregarious nature made her a natural networker."),
    ("Guile",        "n.",   "Sly or cunning intelligence",
     "He managed the negotiation with considerable guile."),
    ("Hackneyed",    "adj.", "Overused and lacking originality",
     "The hackneyed plot offered nothing new."),
    ("Harangue",     "v.",   "To lecture aggressively at length",
     "He harangued his staff over the smallest infractions."),
    ("Hegemony",     "n.",   "Leadership or dominance over others",
     "The empire maintained hegemony over the region."),
    ("Heresy",       "n.",   "Belief contrary to established dogma",
     "Challenging the policy was considered heresy by some."),
    ("Hubris",       "n.",   "Excessive pride or self-confidence",
     "His hubris led him to ignore sound advice."),
    ("Hyperbole",    "n.",   "Exaggerated statements not meant literally",
     "Saying 'I've told you a million times' is hyperbole."),
    ("Iconoclast",   "n.",   "A person who attacks cherished beliefs",
     "The iconoclast challenged every assumption in the field."),
    ("Immutable",    "adj.", "Unchanging over time",
     "The laws of physics are considered immutable."),
    ("Impartial",    "adj.", "Treating all parties equally; fair",
     "The mediator strove to remain impartial."),
    ("Impecunious",  "adj.", "Having little or no money",
     "As a student, she lived an impecunious but happy life."),
    ("Imperturbable","adj.", "Unable to be upset; calm",
     "The surgeon remained imperturbable during the crisis."),
    ("Impetuous",    "adj.", "Acting without thought; rash",
     "His impetuous decision to quit cost him dearly."),
    ("Impinge",      "v.",   "To have a negative effect on",
     "The new rules impinged on individual freedoms."),
    ("Implacable",   "adj.", "Unable to be appeased; relentless",
     "She was an implacable opponent of the policy."),
    ("Impugn",       "v.",   "To dispute the validity or honesty of",
     "The defense sought to impugn the witness's credibility."),
    ("Inchoate",     "adj.", "Just begun and not fully formed",
     "He had an inchoate plan that needed development."),
    ("Incisive",     "adj.", "Clear-thinking; intelligently analytical",
     "Her incisive commentary cut through the rhetoric."),
    ("Incongruous",  "adj.", "Not in harmony with surroundings",
     "A tuxedo at a beach party looked incongruous."),
    ("Inculcate",    "v.",   "To instill an idea by repetition",
     "Parents try to inculcate good values in children."),
    ("Indignant",    "adj.", "Feeling anger at unfair treatment",
     "She was indignant at the accusation of dishonesty."),
    ("Indolent",     "adj.", "Wanting to avoid activity; lazy",
     "His indolent habits prevented him reaching his potential."),
    ("Inept",        "adj.", "Having or showing no skill",
     "The inept contractor left the project unfinished."),
    ("Inert",        "adj.", "Lacking the ability to act; inactive",
     "The inert gases do not react under normal conditions."),
    ("Inexorable",   "adj.", "Impossible to stop or prevent",
     "The inexorable march of time cannot be halted."),
    ("Ingenuous",    "adj.", "Innocent and unsuspecting",
     "Her ingenuous question caught the expert off guard."),
    ("Inimical",     "adj.", "Tending to obstruct or harm; hostile",
     "Such habits are inimical to good health."),
    ("Innate",       "adj.", "Inborn; natural",
     "She had an innate talent for languages."),
    ("Innocuous",    "adj.", "Not harmful or offensive",
     "What seemed innocuous caused unexpected offense."),
    ("Insidious",    "adj.", "Proceeding in a gradual harmful way",
     "The disease spreads in an insidious fashion."),
    ("Insipid",      "adj.", "Lacking flavor or vigor; dull",
     "The insipid performance drew little applause."),
    ("Intractable",  "adj.", "Hard to control or resolve",
     "Poverty is an intractable problem without systemic change."),
    ("Inundate",     "v.",   "To overwhelm with things to deal with",
     "The office was inundated with complaints."),
    ("Irascible",    "adj.", "Easily angered; irritable",
     "The irascible professor had driven away many students."),
    ("Itinerant",    "adj.", "Traveling from place to place for work",
     "He lived the life of an itinerant musician."),
    ("Jargon",       "n.",   "Special words used by a particular group",
     "The document was dense with technical jargon."),
    ("Jocular",      "adj.", "Fond of joking; humorous",
     "His jocular manner put new employees at ease."),
    ("Judicious",    "adj.", "Having sound judgment",
     "A judicious investment in infrastructure paid dividends."),
    ("Laconic",      "adj.", "Using very few words; brief",
     "His laconic reply gave little away."),
    ("Lament",       "v.",   "To express sorrow or regret",
     "She lamented the decline in public discourse."),
    ("Languid",      "adj.", "Showing disinclination for effort",
     "He spent a languid afternoon by the pool."),
    ("Largess",      "n.",   "Generosity in giving money or gifts",
     "The philanthropist's largess funded the new library."),
    ("Latent",       "adj.", "Existing but not yet developed",
     "The talent was latent until a good teacher noticed it."),
    ("Laud",         "v.",   "To praise highly",
     "Critics lauded her debut novel as a masterpiece."),
    ("Lethargic",    "adj.", "Sluggish and apathetic",
     "He felt lethargic for days after the long flight."),
    ("Levity",       "n.",   "Treatment of serious matters without care",
     "A moment of levity helped relieve the tension."),
    ("Loquacious",   "adj.", "Tending to talk a great deal",
     "The loquacious host dominated every conversation."),
    ("Lucid",        "adj.", "Expressed clearly; easy to understand",
     "She gave a lucid explanation of the complex theory."),
    ("Lugubrious",   "adj.", "Looking or sounding sad and dismal",
     "He spoke in a lugubrious voice about the company."),
    ("Magnanimous",  "adj.", "Generous or forgiving toward a rival",
     "The champion was magnanimous in victory."),
    ("Malign",       "v.",   "To speak spitefully critically of",
     "She refused to malign her opponents during the campaign."),
    ("Malleable",    "adj.", "Easily influenced; pliable",
     "Young minds are particularly malleable."),
    ("Mendacious",   "adj.", "Not telling the truth; lying",
     "The mendacious report misled investors for years."),
    ("Mercurial",    "adj.", "Subject to sudden changes of mood",
     "His mercurial temperament made him unpredictable."),
    ("Meticulous",   "adj.", "Showing great attention to detail",
     "The meticulous editor corrected every comma."),
    ("Miscreant",    "n.",   "A person who behaves badly or breaks the law",
     "The miscreant was apprehended by police."),
    ("Mitigate",     "v.",   "To make less severe or serious",
     "His apology did little to mitigate the offence."),
    ("Modicum",      "n.",   "A small quantity of a particular thing",
     "A modicum of caution could have prevented the accident."),
    ("Mollify",      "v.",   "To appease the anger of someone",
     "A sincere apology went a long way to mollify her."),
    ("Morose",       "adj.", "Sullen and ill-tempered",
     "He became morose after hearing the news."),
    ("Mundane",      "adj.", "Lacking interest or excitement; dull",
     "She longed to escape her mundane routine."),
    ("Munificent",   "adj.", "More generous than expected",
     "The munificent donation transformed the charity."),
    ("Naïve",        "adj.", "Showing a lack of experience or judgment",
     "Her naïve trust made her vulnerable to deception."),
    ("Nefarious",    "adj.", "Wicked and criminal",
     "The investigation exposed his nefarious dealings."),
    ("Nonchalant",   "adj.", "Appearing casually calm",
     "She was nonchalant about the award."),
    ("Notorious",    "adj.", "Famous for a bad quality or deed",
     "The street was notorious for petty crime."),
    ("Nuance",       "n.",   "A subtle difference in meaning",
     "He failed to appreciate the nuances of negotiation."),
    ("Obdurate",     "adj.", "Stubbornly refusing to change position",
     "She remained obdurate despite hours of persuasion."),
    ("Obfuscate",    "v.",   "To render obscure or unintelligible",
     "The dense language seemed designed to obfuscate."),
    ("Oblique",      "adj.", "Not explicit or direct; indirect",
     "His oblique references left everyone guessing."),
    ("Oblivious",    "adj.", "Not aware of or concerned about",
     "She was oblivious to the impact of her words."),
    ("Obstinate",    "adj.", "Stubbornly refusing to change opinion",
     "His obstinate refusal stalled the talks."),
    ("Obtuse",       "adj.", "Annoyingly insensitive or slow to understand",
     "He was deliberately obtuse to avoid the question."),
    ("Officious",    "adj.", "Asserting authority in an intrusive way",
     "The officious clerk demanded three forms of ID."),
    ("Ominous",      "adj.", "Suggesting something bad will happen",
     "Dark clouds gathered in an ominous sky."),
    ("Opaque",       "adj.", "Not transparent; difficult to understand",
     "The financial statements were deliberately opaque."),
    ("Opprobrium",   "n.",   "Harsh criticism or censure",
     "The policy attracted widespread public opprobrium."),
    ("Ostracize",    "v.",   "To exclude from a society or group",
     "Those who broke the code were ostracized."),
    ("Overwrought",  "adj.", "In a state of excessive agitation",
     "She was overwrought after hours of searching."),
    ("Panacea",      "n.",   "A solution to all difficulties",
     "Technology is not a panacea for social problems."),
    ("Paradox",      "n.",   "A statement that may contradict itself but be true",
     "The paradox of choice suggests more options can paralyze."),
    ("Pariah",       "n.",   "A person excluded from society; outcast",
     "After the scandal, he became a pariah in the industry."),
    ("Parsimonious", "adj.", "Excessively unwilling to spend money",
     "His parsimonious nature prevented him from enjoying life."),
    ("Partisan",     "adj.", "Prejudiced in favor of a particular cause",
     "The coverage was seen as partisan by many."),
    ("Paucity",      "n.",   "Presence of something in small quantities",
     "There was a paucity of evidence to support the claim."),
    ("Pedantic",     "adj.", "Overly concerned with minor details",
     "His pedantic corrections annoyed casual readers."),
    ("Penury",       "n.",   "The state of being very poor",
     "Years of neglect plunged the family into penury."),
    ("Perfidious",   "adj.", "Deceitful and untrustworthy",
     "The perfidious ally switched sides at the worst moment."),
    ("Perfunctory",  "adj.", "Carried out with minimal effort",
     "He gave a perfunctory nod and walked away."),
    ("Pernicious",   "adj.", "Having a harmful effect gradually",
     "The pernicious rumors damaged his reputation."),
    ("Petulant",     "adj.", "Childishly sulky or bad-tempered",
     "She gave a petulant reply when asked to wait."),
    ("Philanthropy", "n.",   "Desire to promote the welfare of others",
     "His philanthropy has funded hundreds of scholarships."),
    ("Pithy",        "adj.", "Brief, forceful, and meaningful",
     "The pithy summary captured the essence of the argument."),
    ("Placate",      "v.",   "To make someone less angry or hostile",
     "Management tried to placate workers with concessions."),
    ("Platitude",    "n.",   "An overused remark that conveys little",
     "His speech was full of platitudes that moved no one."),
    ("Plausible",    "adj.", "Seeming reasonable or probable",
     "She offered a plausible explanation for her absence."),
    ("Polarize",     "v.",   "To divide into sharply contrasting groups",
     "The issue polarized public opinion overnight."),
    ("Polemical",    "adj.", "Controversial; involving debate",
     "His polemical essays provoked strong reactions."),
    ("Ponderous",    "adj.", "Slow and clumsy; pompously dull",
     "The ponderous prose made the novel hard to finish."),
    ("Pragmatic",    "adj.", "Dealing with things realistically",
     "A pragmatic approach to the crisis saved time."),
    ("Precarious",   "adj.", "Dangerously uncertain",
     "The company was in a precarious financial position."),
    ("Precipitous",  "adj.", "Dangerously steep; hasty",
     "A precipitous drop in revenue alarmed shareholders."),
    ("Precocious",   "adj.", "Developed at an unusually early age",
     "The precocious child read novels at age five."),
    ("Prescient",    "adj.", "Having knowledge of events before they happen",
     "His prescient warning went unheeded at the time."),
    ("Presumptuous", "adj.", "Too bold; overstepping boundaries",
     "It was presumptuous to assume she would agree."),
    ("Prevaricate",  "v.",   "To speak evasively; avoid commitment",
     "Stop prevaricating and give us a direct answer."),
    ("Pristine",     "adj.", "In its original condition; unspoilt",
     "The archive kept the manuscripts in pristine condition."),
    ("Probity",      "n.",   "Strong moral principles; integrity",
     "Voters valued the candidate's reputation for probity."),
    ("Proclivity",   "n.",   "A tendency to do something regularly",
     "Her proclivity for perfectionism served her well."),
    ("Prodigal",     "adj.", "Spending money recklessly",
     "The prodigal heir squandered his inheritance."),
    ("Prodigious",   "adj.", "Remarkably great in extent or degree",
     "She read with prodigious speed and retained everything."),
    ("Profound",     "adj.", "Very great or intense; having deep insight",
     "The loss had a profound effect on his outlook."),
    ("Profuse",      "adj.", "Given lavishly; abundant",
     "He offered profuse apologies for the misunderstanding."),
    ("Propitious",   "adj.", "Indicating a good chance of success",
     "The timing seemed propitious for the initiative."),
    ("Prosaic",      "adj.", "Lacking imagination; dull",
     "His descriptions were prosaic and uninspired."),
    ("Prudent",      "adj.", "Acting with care for the future",
     "A prudent investor diversifies their portfolio."),
    ("Querulous",    "adj.", "Complaining in a whining manner",
     "The querulous customer complained about every detail."),
    ("Quiescent",    "adj.", "In a state of inactivity or dormancy",
     "The volcano appeared quiescent but was closely monitored."),
    ("Quixotic",     "adj.", "Exceedingly idealistic and unrealistic",
     "His quixotic quest for a perfect society inspired many."),
    ("Recalcitrant", "adj.", "Obstinately uncooperative",
     "The recalcitrant student refused every offer of help."),
    ("Rectitude",    "n.",   "Morally correct behavior",
     "His reputation for rectitude was his greatest asset."),
    ("Redoubtable",  "adj.", "Formidable, especially as an opponent",
     "She was a redoubtable debater who rarely lost."),
    ("Refractory",   "adj.", "Stubborn or unmanageable",
     "The refractory child defied every rule."),
    ("Refute",       "v.",   "To prove a statement wrong",
     "The scientist refuted the popular theory."),
    ("Relegate",     "v.",   "To consign to an inferior position",
     "The memo was relegated to the bottom of the pile."),
    ("Remorse",      "n.",   "Deep regret or guilt for a wrongdoing",
     "He expressed genuine remorse for his actions."),
    ("Renounce",     "v.",   "To formally declare abandonment of a claim",
     "He renounced his citizenship in protest."),
    ("Reprehensible","adj.", "Deserving censure or condemnation",
     "The committee called his behavior reprehensible."),
    ("Reprove",      "v.",   "To rebuke or censure",
     "The supervisor reproved him for missing the deadline."),
    ("Repudiate",    "v.",   "To refuse to accept or be associated with",
     "She repudiated the allegations of fraud."),
    ("Rescind",      "v.",   "To revoke, cancel, or repeal",
     "The court ordered the contract to be rescinded."),
    ("Resilient",    "adj.", "Able to recover quickly from difficulties",
     "The resilient team rebounded after a crushing defeat."),
    ("Reticent",     "adj.", "Not revealing one's feelings readily",
     "He was reticent about his personal struggles."),
    ("Rhetoric",     "n.",   "Language designed to be persuasive",
     "His rhetoric was powerful but short on substance."),
    ("Rigorous",     "adj.", "Extremely thorough and careful",
     "The training program was rigorous and demanding."),
    ("Ruse",         "n.",   "An action intended to deceive",
     "The phone call was a ruse to get him out of the office."),
    ("Sagacious",    "adj.", "Having keen mental discernment",
     "The sagacious elder advised caution."),
    ("Sanctimonious","adj.", "Showing off moral superiority",
     "His sanctimonious lecture irritated everyone."),
    ("Sanguine",     "adj.", "Optimistic in a difficult situation",
     "She remained sanguine despite the setbacks."),
    ("Sardonic",     "adj.", "Grimly mocking or cynical",
     "He watched the ceremony with a sardonic smile."),
    ("Scrupulous",   "adj.", "Extremely attentive to what is right",
     "A scrupulous auditor leaves no stone unturned."),
    ("Sedulously",   "adv.", "With dedicated and diligent application",
     "She sedulously reviewed every page of the contract."),
    ("Solicitous",   "adj.", "Showing concern and care",
     "The nurse was solicitous of the patient's comfort."),
    ("Soporific",    "adj.", "Tending to induce sleep",
     "The lecturer's monotone voice was soporific."),
    ("Specious",     "adj.", "Superficially plausible but actually wrong",
     "The argument was specious and easily dismantled."),
    ("Spurious",     "adj.", "Not what it purports to be; false",
     "The document was found to be a spurious copy."),
    ("Squalid",      "adj.", "Extremely dirty and unpleasant",
     "The squalid conditions appalled inspectors."),
    ("Stoic",        "adj.", "Enduring pain without showing feelings",
     "She faced her illness with stoic determination."),
    ("Strident",     "adj.", "Loud and harsh; aggressively forceful",
     "His strident demands alienated potential supporters."),
    ("Stymie",       "v.",   "To prevent or hinder the progress of",
     "Bureaucratic delays stymied the investigation."),
    ("Subvert",      "v.",   "To undermine the power of a system",
     "The conspiracy sought to subvert democratic processes."),
    ("Supercilious", "adj.", "Behaving as if superior; disdainful",
     "The supercilious waiter made dining unpleasant."),
    ("Sycophant",    "n.",   "A person who flatters to gain advantage",
     "His cabinet was filled with sycophants."),
    ("Tacit",        "adj.", "Understood without being stated",
     "There was a tacit agreement not to discuss the matter."),
    ("Taciturn",     "adj.", "Reserved or uncommunicative in speech",
     "He was taciturn by nature, preferring to listen."),
    ("Tangential",   "adj.", "Diverging from the subject; not central",
     "His remarks were tangential to the main discussion."),
    ("Temerity",     "n.",   "Excessive confidence or boldness",
     "She had the temerity to question the CEO openly."),
    ("Tenacious",    "adj.", "Tending to keep a firm hold; persistent",
     "A tenacious reporter eventually uncovered the truth."),
    ("Terse",        "adj.", "Sparing in words; abrupt",
     "His terse reply signaled the meeting was over."),
    ("Timorous",     "adj.", "Showing nervousness or fear",
     "The timorous student barely spoke above a whisper."),
    ("Torpor",       "n.",   "A state of physical or mental inactivity",
     "After lunch, the team fell into a comfortable torpor."),
    ("Tortuous",     "adj.", "Full of twists; excessively complicated",
     "The tortuous mountain road tested every driver."),
    ("Tractable",    "adj.", "Easy to deal with; manageable",
     "The tractable pupil absorbed every lesson quickly."),
    ("Transient",    "adj.", "Lasting only for a short time",
     "Fame in the internet age can be entirely transient."),
    ("Trite",        "adj.", "Overused and lacking originality",
     "He resorted to trite phrases that conveyed nothing."),
    ("Truculent",    "adj.", "Eager to argue; aggressively defiant",
     "The truculent suspect refused to cooperate."),
    ("Turgid",       "adj.", "Swollen; pompously inflated in style",
     "The turgid prose made the report painful to read."),
    ("Turpitude",    "n.",   "Wickedness and depravity",
     "He was dismissed for moral turpitude."),
    ("Ubiquitous",   "adj.", "Present or found everywhere",
     "Smartphones have become ubiquitous in modern life."),
    ("Unctuous",     "adj.", "Excessively flattering; oily",
     "The unctuous salesman made everyone uncomfortable."),
    ("Undermine",    "v.",   "To weaken or damage gradually",
     "Constant criticism can undermine a person's confidence."),
    ("Unequivocal",  "adj.", "Leaving no doubt; unambiguous",
     "Her unequivocal support strengthened the movement."),
    ("Upbraid",      "v.",   "To find fault with; to scold",
     "He upbraided the team for failing to prepare."),
    ("Vacillate",    "v.",   "To waver between opinions or actions",
     "She vacillated between two career paths for years."),
    ("Vacuous",      "adj.", "Lacking thought or intelligence",
     "The vacuous interview wasted ten minutes."),
    ("Venerate",     "v.",   "To regard with great respect",
     "The community venerated the elder as a living legend."),
    ("Verbose",      "adj.", "Using more words than necessary",
     "His verbose report could have been half the length."),
    ("Vex",          "v.",   "To make someone feel annoyed or puzzled",
     "The unsolved problem vexed the mathematician."),
    ("Vilify",       "v.",   "To speak abusively critically of",
     "The tabloids sought to vilify the whistleblower."),
    ("Vindicate",    "v.",   "To clear of blame or suspicion",
     "The ruling vindicated her long-held position."),
    ("Virulent",     "adj.", "Extremely harmful or malicious",
     "A virulent strain swept through the region."),
    ("Vitriolic",    "adj.", "Filled with bitter criticism or malice",
     "His vitriolic attack left the audience uncomfortable."),
    ("Vociferous",   "adj.", "Expressing opinions loudly and forcefully",
     "Vociferous protesters gathered outside the courthouse."),
    ("Volatile",     "adj.", "Liable to change rapidly and unpredictably",
     "The volatile market unsettled even experienced traders."),
    ("Voracious",    "adj.", "Wanting or devouring great quantities",
     "He was a voracious reader who finished a book each day."),
    ("Wary",         "adj.", "Feeling cautious about possible dangers",
     "She was wary of signing without legal advice."),
    ("Whimsical",    "adj.", "Playfully quaint or fanciful",
     "The children loved his whimsical illustrations."),
    ("Zealous",      "adj.", "Having great energy or enthusiasm",
     "The zealous intern arrived an hour before everyone else."),
    ("Zenith",       "n.",   "The time at which something is most powerful",
     "At the zenith of her career she had no equal."),
    ("Zephyr",       "n.",   "A soft, gentle breeze",
     "A cool zephyr drifted through the open window."),
    # ── 166 additional entries (total = 525) ──────────────────────────────
    ("Abase",        "v.",   "To lower in rank or esteem",
     "He refused to abase himself before the tyrant."),
    ("Abash",        "v.",   "To make someone feel embarrassed",
     "She was not abashed by the public attention."),
    ("Aberration",   "n.",   "A departure from the normal or expected",
     "The cold spell in July was a meteorological aberration."),
    ("Abhor",        "v.",   "To regard with disgust and hatred",
     "She abhorred injustice in all its forms."),
    ("Abrogate",     "v.",   "To repeal or do away with a law or practice",
     "The treaty was abrogated after years of dispute."),
    ("Absolution",   "n.",   "Formal release from guilt or penalty",
     "He sought absolution for the wrongs he had committed."),
    ("Accretion",    "n.",   "Growth or increase by gradual addition",
     "The accretion of small savings built real wealth."),
    ("Accolade",     "n.",   "An award or expression of praise",
     "She received the highest accolade in her profession."),
    ("Acrimony",     "n.",   "Bitterness or ill feeling in manner",
     "The negotiations were characterized by acrimony."),
    ("Adamant",      "adj.", "Refusing to be persuaded; unshakeable",
     "He was adamant that the project would succeed."),
    ("Adhere",       "v.",   "To stick firmly to; to follow closely",
     "She adhered to the highest ethical standards."),
    ("Adjudicate",   "v.",   "To make a formal judgment on a matter",
     "A panel was appointed to adjudicate the dispute."),
    ("Admonition",   "n.",   "A firm warning or cautionary advice",
     "He took the admonition to heart and corrected course."),
    ("Advocate",     "n.",   "A person who supports or defends a cause",
     "She became a tireless advocate for public health."),
    ("Aesthetic",    "n.",   "A set of principles underlying artistic work",
     "The designer's aesthetic emphasized clean lines."),
    ("Affinity",     "n.",   "A natural liking for something",
     "She had a clear affinity for mathematics."),
    ("Aggregate",    "v.",   "To collect into a mass or whole",
     "The data was aggregated from thousands of responses."),
    ("Amiable",      "adj.", "Having a pleasant and friendly manner",
     "The amiable professor was beloved by all students."),
    ("Amorphous",    "adj.", "Without a clearly defined shape or form",
     "The plan remained amorphous and needed structure."),
    ("Anarchy",      "n.",   "A state of disorder due to absent authority",
     "Without leadership, the project descended into anarchy."),
    ("Animus",       "n.",   "Hostility or ill feeling",
     "There was obvious animus between the rival factions."),
    ("Annex",        "v.",   "To add or attach as an extra part",
     "The empire annexed the smaller territory peacefully."),
    ("Antipathy",    "n.",   "A deep-seated feeling of aversion",
     "His antipathy toward injustice shaped his career."),
    ("Antithesis",   "n.",   "The direct opposite of something",
     "Her calm demeanor was the antithesis of his panic."),
    ("Apocryphal",   "adj.", "Of doubtful authenticity or authorship",
     "Many of the stories about him are apocryphal."),
    ("Ardor",        "n.",   "Enthusiasm or passion",
     "She pursued the research with great ardor."),
    ("Arrant",       "adj.", "Complete; utter (used of unpleasant things)",
     "That claim is arrant nonsense."),
    ("Aspersion",    "n.",   "An attack on the reputation or integrity of",
     "He cast aspersions on her professional conduct."),
    ("Asperity",     "n.",   "Harshness of tone or manner",
     "She replied with asperity that surprised everyone."),
    ("Assail",       "v.",   "To attack vigorously or violently",
     "The plan was assailed from all sides."),
    ("Attestation",  "n.",   "Evidence or proof of something",
     "The signature served as attestation of authenticity."),
    ("Augment",      "v.",   "To make something greater in size or value",
     "Extra funding augmented the research capacity."),
    ("Auspicious",   "adj.", "Giving or indicating a good start",
     "The project began under auspicious circumstances."),
    ("Avarice",      "n.",   "Extreme greed for material gain",
     "His avarice alienated everyone around him."),
    ("Aversion",     "n.",   "A strong dislike or disinclination",
     "She had a deep aversion to confrontation."),
    ("Badger",       "v.",   "To repeatedly pester someone",
     "Journalists badgered the spokesperson for answers."),
    ("Baleful",      "adj.", "Threatening harm; menacing",
     "He shot a baleful glance at the intruder."),
    ("Banter",       "n.",   "Playful and friendly exchange of teasing",
     "The team's banter kept morale high."),
    ("Belittle",     "v.",   "To make someone feel unimportant",
     "She refused to belittle her competitors."),
    ("Bemoan",       "v.",   "To express discontent or sorrow about",
     "He bemoaned the lack of public investment."),
    ("Bequeath",     "v.",   "To leave property by a will",
     "She bequeathed her library to the university."),
    ("Bewilder",     "v.",   "To cause someone to become perplexed",
     "The contradictory evidence bewildered investigators."),
    ("Blandishment", "n.",   "Flattery intended to persuade someone",
     "No amount of blandishment could sway her opinion."),
    ("Boisterous",   "adj.", "Noisy, energetic, and cheerful",
     "The boisterous crowd welcomed the champion home."),
    ("Candid",       "adj.", "Truthful and straightforward",
     "She was always candid about her limitations."),
    ("Capitulate",   "v.",   "To cease to resist an opponent; to yield",
     "He finally capitulated after hours of negotiation."),
    ("Catalyst",     "n.",   "An event that causes change to happen",
     "The book was a catalyst for the social movement."),
    ("Cavil",        "v.",   "To make petty objections",
     "He was always ready to cavil at minor procedural details."),
    ("Censorious",   "adj.", "Severely critical of others",
     "The censorious reviewer found fault with everything."),
    ("Charlatan",    "n.",   "A person falsely claiming expertise",
     "The so-called expert was exposed as a charlatan."),
    ("Chide",        "v.",   "To scold or rebuke",
     "She chided him for arriving late again."),
    ("Cogitate",     "v.",   "To think carefully about something",
     "He cogitated for hours before making the decision."),
    ("Combustible",  "adj.", "Able to catch fire easily; easily excited",
     "The situation was politically combustible."),
    ("Compunction",  "n.",   "A feeling of guilt about doing something",
     "She felt no compunction about her firm stance."),
    ("Conceit",      "n.",   "Excessive pride in oneself",
     "His conceit blinded him to his own shortcomings."),
    ("Contrite",     "adj.", "Feeling or expressing remorse",
     "He was genuinely contrite after causing harm."),
    ("Convivial",    "adj.", "Friendly and lively; relating to good company",
     "The convivial dinner lasted well into the night."),
    ("Credulous",    "adj.", "Having too great a readiness to believe",
     "A credulous audience accepted every claim."),
    ("Cupidity",     "n.",   "Greed for money or possessions",
     "Cupidity drove the executive to defraud investors."),
    ("Dearth",       "n.",   "A scarcity or lack of something",
     "There was a dearth of qualified candidates."),
    ("Decry",        "v.",   "To publicly denounce",
     "Activists decried the new legislation."),
    ("Deleterious",  "adj.", "Causing harm or damage",
     "The deleterious effects of pollution are well-documented."),
    ("Demagogy",     "n.",   "Political activity based on manipulation",
     "His rise to power relied heavily on demagogy."),
    ("Demure",       "adj.", "Reserved, modest, and shy",
     "The demure candidate spoke only when spoken to."),
    ("Denigrate",    "v.",   "To criticize unfairly; to belittle",
     "He denigrated opponents rather than engaging their ideas."),
    ("Denizen",      "n.",   "An inhabitant or occupant of a place",
     "Owls are secretive denizens of the forest."),
    ("Deplete",      "v.",   "To reduce something in quantity",
     "Overfishing has depleted the ocean's stocks."),
    ("Derelict",     "adj.", "In poor condition due to neglect",
     "The derelict building was finally demolished."),
    ("Derogatory",   "adj.", "Showing a critical or disrespectful attitude",
     "Derogatory remarks have no place in the workplace."),
    ("Dictum",       "n.",   "A formal pronouncement from authority",
     "The legal dictum was cited in every subsequent case."),
    ("Diffuse",      "v.",   "To spread over a wide area",
     "New ideas diffused rapidly through the community."),
    ("Dilatory",     "adj.", "Slow to act; causing delay",
     "His dilatory response frustrated the client."),
    ("Discordant",   "adj.", "Not in agreement; conflicting",
     "Discordant voices made consensus impossible."),
    ("Disingenuous", "adj.", "Not candid or sincere; calculating",
     "His apparent concern was utterly disingenuous."),
    ("Disparage",    "v.",   "To speak of in a slighting way",
     "She never disparaged her colleagues in public."),
    ("Disputatious", "adj.", "Fond of causing arguments",
     "The disputatious senator blocked every proposal."),
    ("Dissonant",    "adj.", "Lacking agreement or harmony",
     "The dissonant notes created an uneasy atmosphere."),
    ("Dogma",        "n.",   "A principle or set of principles laid down by authority",
     "He was unwilling to question the party's dogma."),
    ("Dormant",      "adj.", "Inactive but capable of becoming active",
     "The dormant talent emerged under the right mentor."),
    ("Draconian",    "adj.", "Excessively harsh or severe",
     "Draconian laws were imposed after the uprising."),
    ("Dubious",      "adj.", "Hesitating or doubting; not reliable",
     "The evidence supporting the claim was dubious."),
    ("Edict",        "n.",   "An official order issued by authority",
     "The king issued an edict banning public protest."),
    ("Effete",       "adj.", "Affected, over-refined, and feeble",
     "His effete manner struck newcomers as pretentious."),
    ("Effusive",     "adj.", "Expressing feelings in an unrestrained way",
     "She received effusive praise from the audience."),
    ("Elucidate",    "v.",   "To make something clear; to explain",
     "The diagram helped elucidate the complex process."),
    ("Eminent",      "adj.", "Famous and respected within a field",
     "An eminent scholar was invited to give the keynote."),
    ("Empiricism",   "n.",   "Theory that knowledge comes from experience",
     "Empiricism underpins the modern scientific method."),
    ("Encumber",     "v.",   "To restrict or burden",
     "Heavy debt encumbered the company's growth."),
    ("Ennui",        "n.",   "A feeling of listlessness and dissatisfaction",
     "After a month of idleness, ennui set in."),
    ("Equanimity",   "n.",   "Mental calmness in difficult situations",
     "She accepted the bad news with remarkable equanimity."),
    ("Erratic",      "adj.", "Not even or regular; unpredictable",
     "His erratic schedule made collaboration difficult."),
    ("Evasive",      "adj.", "Tending to avoid commitment or directness",
     "The witness gave evasive answers throughout."),
    ("Exacting",     "adj.", "Making great demands; requiring care",
     "The exacting editor returned every manuscript annotated."),
    ("Exemplary",    "adj.", "Serving as a desirable model",
     "Her exemplary conduct was held up by management."),
    ("Exhaustive",   "adj.", "Including all possibilities; thorough",
     "An exhaustive review found no procedural error."),
    ("Expunge",      "v.",   "To obliterate or remove completely",
     "The court ordered the record to be expunged."),
    ("Exult",        "v.",   "To show or feel elation or jubilation",
     "The team exulted when the final whistle blew."),
    ("Facile",       "adj.", "Appearing ready without effort; superficial",
     "His facile charm won admirers but few trusted him."),
    ("Fallacy",      "n.",   "A mistaken belief based on flawed reasoning",
     "The idea that correlation implies causation is a fallacy."),
    ("Fathom",       "v.",   "To understand after much thought",
     "She could not fathom his decision to resign."),
    ("Fastidious",   "adj.", "Very attentive to accuracy and detail",
     "The fastidious chef tasted every dish before service."),
    ("Feign",        "v.",   "To pretend to feel or be affected by",
     "He feigned surprise at the announcement."),
    ("Felicity",     "n.",   "Intense happiness; the ability to find apt expression",
     "She described the scene with great felicity."),
    ("Ferocious",    "adj.", "Savagely fierce, cruel, or violent",
     "The team trained with ferocious intensity."),
    ("Flagrant",     "adj.", "Conspicuously or obviously offensive",
     "It was a flagrant breach of the rules."),
    ("Flummox",      "v.",   "To perplex or bewilder",
     "The unexpected question flummoxed the expert."),
    ("Frugal",       "adj.", "Sparing or economical with money",
     "Her frugal habits allowed her to save a fortune."),
    ("Fulsome",      "adj.", "Excessively complimentary; insincere",
     "His fulsome praise struck many as hollow."),
    ("Galvanize",    "v.",   "To shock or excite someone into action",
     "The crisis galvanized the community into action."),
    ("Garner",       "v.",   "To gather or collect",
     "The petition garnered thousands of signatures."),
    ("Gaunt",        "adj.", "Lean and haggard, especially from illness",
     "He looked gaunt after months of overwork."),
    ("Genial",       "adj.", "Friendly and cheerful",
     "The genial host welcomed every guest warmly."),
    ("Germane",      "adj.", "Relevant to a subject under consideration",
     "Her comment was germane to the discussion."),
    ("Glut",         "n.",   "An excessively abundant supply",
     "A glut of cheap imports hurt local manufacturers."),
    ("Gourmand",     "n.",   "A person who enjoys eating and often eats too much",
     "The gourmand sampled every dish on the menu."),
    ("Hapless",      "adj.", "Unfortunate; having no luck",
     "The hapless traveler missed every connection."),
    ("Haughty",      "adj.", "Arrogantly superior and disdainful",
     "His haughty manner put off potential allies."),
    ("Heretical",    "adj.", "Holding beliefs contrary to orthodoxy",
     "Her heretical view challenged decades of tradition."),
    ("Heuristic",    "adj.", "Enabling someone to discover or learn for themselves",
     "A heuristic approach helped students find answers."),
    ("Histrionic",   "adj.", "Excessively theatrical or dramatic",
     "His histrionic response was widely mocked."),
    ("Homogeneous",  "adj.", "Of the same kind; uniform",
     "The neighborhood grew less homogeneous over time."),
    ("Hypocrite",    "n.",   "A person who claims beliefs they do not follow",
     "He was branded a hypocrite by his own followers."),
    ("Idiosyncratic","adj.", "Peculiar to an individual",
     "Her idiosyncratic style was instantly recognizable."),
    ("Ignominious",  "adj.", "Deserving or causing public shame",
     "The campaign ended in ignominious defeat."),
    ("Illusory",     "adj.", "Based on illusion; not real",
     "The sense of security proved entirely illusory."),
    ("Impasse",      "n.",   "A situation with no way forward",
     "Negotiations reached an impasse over pay."),
    ("Implacability","n.",   "The quality of being impossible to appease",
     "Her implacability made compromise impossible."),
    ("Implicit",     "adj.", "Implied though not directly expressed",
     "There was implicit criticism in his silence."),
    ("Impudent",     "adj.", "Failing to show proper respect",
     "The impudent reply shocked the committee."),
    ("Incandescent", "adj.", "Full of intense emotion; furious",
     "She was incandescent with rage at the verdict."),
    ("Indeterminate","adj.", "Not exactly known or established",
     "The outcome remained indeterminate for weeks."),
    ("Indurate",     "v.",   "To make callous or insensitive",
     "Years of combat had indurated him to suffering."),
    ("Ineffable",    "adj.", "Too great or extreme to be expressed",
     "She experienced an ineffable sense of peace."),
    ("Infer",        "v.",   "To conclude from evidence and reasoning",
     "From the data, she inferred a clear pattern."),
    ("Ingratiate",   "v.",   "To bring oneself into favor by flattery",
     "He tried to ingratiate himself with the new boss."),
    ("Injunction",   "n.",   "A court order requiring action or restraint",
     "The court issued an injunction halting the project."),
    ("Insular",      "adj.", "Ignorant of or uninterested in outside world",
     "His insular outlook limited professional growth."),
    ("Intemperate",  "adj.", "Having or showing a lack of self-control",
     "His intemperate remarks derailed the meeting."),
    ("Intransigent", "adj.", "Refusing to change one's views",
     "The intransigent negotiator blocked every proposal."),
    ("Invidious",    "adj.", "Likely to arouse resentment or anger",
     "Making invidious comparisons serves no one."),
    ("Irrefutable",  "adj.", "Impossible to deny or disprove",
     "The evidence was irrefutable."),
    ("Lachrymose",   "adj.", "Tearful or inducing tears",
     "The lachrymose farewell moved everyone present."),
    ("Lassitude",    "n.",   "Physical or mental weariness",
     "The oppressive heat induced a general lassitude."),
    ("Laudatory",    "adj.", "Expressing praise",
     "The laudatory review boosted ticket sales."),
    ("Limpid",       "adj.", "Clear and transparent",
     "The limpid prose was a pleasure to read."),
    ("Lionize",      "v.",   "To treat someone as a celebrity",
     "The media lionized the young inventor."),
    ("Litigious",    "adj.", "Inclined to resolve disputes in court",
     "The litigious company filed dozens of suits annually."),
    ("Maladroit",    "adj.", "Ineffective or bungling; clumsy",
     "His maladroit handling of the crisis worsened things."),
    ("Maverick",     "n.",   "An independent thinker who avoids conformity",
     "She was considered a maverick within the institution."),
    ("Mawkish",      "adj.", "Sentimental in a feeble or sickly way",
     "The mawkish ending disappointed critical readers."),
    ("Meretricious", "adj.", "Apparently attractive but having low value",
     "The meretricious offer concealed many drawbacks."),
    ("Mirth",        "n.",   "Amusement, especially as expressed in laughter",
     "His joke provoked great mirth around the table."),
    ("Misanthrope",  "n.",   "A person who dislikes humankind",
     "The reclusive misanthrope avoided all social events."),
    ("Misnomer",     "n.",   "A wrong or inaccurate name",
     "'Tin foil' is a misnomer—it's actually aluminum foil."),
    ("Mollification","n.",   "The act of pacifying or appeasing",
     "The policy change was offered as mollification."),
    ("Moot",         "adj.", "Subject to debate; having no practical significance",
     "Whether to invest was moot once funding dried up."),
    ("Morbid",       "adj.", "Having an unhealthy interest in death",
     "His morbid curiosity alarmed his friends."),
    ("Nebulous",     "adj.", "Unclear; vague; hazy",
     "The proposal was too nebulous to gain approval."),
    ("Neologism",    "n.",   "A newly coined word or expression",
     "'Selfie' is a neologism that entered dictionaries quickly."),
    ("Nihilism",     "n.",   "Belief that life is meaningless",
     "His nihilism prevented him from committing to any cause."),
    ("Obsequious",   "adj.", "Excessively eager to serve or please",
     "The obsequious assistant agreed with everything said."),
    ("Odious",       "adj.", "Extremely unpleasant; repulsive",
     "The odious practice was finally banned."),
    ("Onerous",      "adj.", "Involving heavy obligations; burdensome",
     "The onerous paperwork discouraged many applicants."),
    ("Palatial",     "adj.", "Resembling a palace; spacious and splendid",
     "The palatial headquarters impressed every visitor."),
    ("Palliate",     "v.",   "To make less severe without removing the cause",
     "Medication can palliate symptoms but not cure the disease."),
    ("Paltry",       "adj.", "Petty; contemptibly small or poor",
     "The paltry raise failed to retain key staff."),
    ("Paradigm",     "n.",   "A typical example or pattern of something",
     "The discovery shifted the entire scientific paradigm."),
    ("Paramour",     "n.",   "A lover, especially one in an adulterous relationship",
     "The scandal involved a well-known political paramour."),
    ("Paragon",      "n.",   "A person or thing regarded as a perfect example",
     "She was considered a paragon of professional conduct."),
    ("Parochial",    "adj.", "Concerned only with local matters; narrow",
     "His parochial worldview limited his foreign policy thinking."),
    ("Pathos",       "n.",   "A quality evoking sadness or pity",
     "The film's ending was full of genuine pathos."),
    ("Penchant",     "n.",   "A strong tendency to do something",
     "She had a penchant for taking on impossible challenges."),
    ("Perennial",    "adj.", "Lasting or existing for a long time",
     "Traffic congestion is a perennial urban problem."),
    ("Perturb",      "v.",   "To make someone anxious or unsettled",
     "The unexpected data perturbed the research team."),
    ("Phlegmatic",   "adj.", "Having an unemotional and stolidly calm manner",
     "His phlegmatic response surprised the hostile reporters."),
    ("Placid",       "adj.", "Not easily upset or excited; calm",
     "Despite the chaos, she remained placid."),
    ("Polemic",      "n.",   "A strong verbal or written attack on someone",
     "His polemic against inequality resonated widely."),
    ("Pompous",      "adj.", "Affectedly grand or solemn",
     "The pompous chairman opened every meeting with a speech."),
    ("Posit",        "v.",   "To put forward as fact or as a basis for argument",
     "She posited that early intervention improves outcomes."),
    ("Posterity",    "n.",   "All future generations of people",
     "They preserved the archives for posterity."),
    ("Precipitate",  "v.",   "To cause something to happen suddenly",
     "The announcement precipitated a sell-off."),
    ("Proponent",    "n.",   "A person who advocates for something",
     "She was a leading proponent of renewable energy."),
    ("Propriety",    "n.",   "Conformity with what is socially acceptable",
     "He observed every rule of social propriety."),
    ("Pugnacious",   "adj.", "Eager or quick to argue or fight",
     "His pugnacious style made him a difficult colleague."),
    ("Punctilious",  "adj.", "Showing great attention to detail or correct behavior",
     "She was punctilious about acknowledging sources."),
    ("Pusillanimous","adj.", "Showing a lack of courage; timid",
     "His pusillanimous retreat cost him respect."),
    ("Rancor",       "n.",   "Bitterness or resentfulness",
     "Years of rancor between the families finally ended."),
    ("Raze",         "v.",   "To completely destroy a building or town",
     "The old quarter was razed to make way for development."),
    ("Recant",       "v.",   "To say that one no longer holds a belief",
     "Under pressure, he recanted his earlier statement."),
    ("Reclusive",    "adj.", "Avoiding the company of others",
     "The reclusive author rarely gave interviews."),
    ("Redolent",     "adj.", "Strongly reminiscent or suggestive of",
     "Her writing was redolent of the Victorian era."),
    ("Refulgent",    "adj.", "Shining brightly; radiant",
     "The refulgent sky at sunset drew gasps of admiration."),
    ("Remonstrate",  "v.",   "To make a protest; to argue forcefully",
     "She remonstrated with the board over the decision."),
    ("Replete",      "adj.", "Filled or well-supplied with something",
     "The library was replete with rare manuscripts."),
    ("Reproach",     "v.",   "To address someone with disapproval",
     "He reproached himself for the missed opportunity."),
    ("Reprobate",    "n.",   "A person without moral principles",
     "The reprobate had a long list of misdemeanors."),
    ("Resolute",     "adj.", "Admirably purposeful; determined",
     "She remained resolute despite fierce opposition."),
    ("Reticence",    "n.",   "The quality of being reserved or uncommunicative",
     "His reticence on personal matters was well-known."),
    ("Reverence",    "n.",   "Deep respect for someone or something",
     "She spoke of her mentor with reverence."),
    ("Rudimentary",  "adj.", "Involving basic principles; undeveloped",
     "His understanding of law was rudimentary at best."),
    ("Ruminate",     "v.",   "To think deeply about something",
     "He ruminated on the problem for several days."),
    ("Satire",       "n.",   "The use of humor to criticize folly",
     "Political satire flourished during the election."),
    ("Saucy",        "adj.", "Boldly disrespectful in a lively way",
     "Her saucy reply amused the audience."),
    ("Schism",       "n.",   "A split or division between opposing groups",
     "The vote created a schism in the party."),
    ("Secular",      "adj.", "Not connected with religious matters",
     "The ceremony was entirely secular in character."),
    ("Sedition",     "n.",   "Conduct or speech inciting rebellion",
     "He was charged with sedition by the state."),
    ("Servile",      "adj.", "Having or showing an excessive willingness to serve",
     "Servile compliance replaced honest debate."),
    ("Sinuous",      "adj.", "Having many curves; lithe and supple",
     "The river followed a sinuous path through the valley."),
    ("Sober",        "adj.", "Serious, sensible, and solemn",
     "He offered a sober assessment of the risks."),
    ("Solace",       "n.",   "Comfort or consolation in distress",
     "She found solace in her books during hard times."),
    ("Sophistry",    "n.",   "Use of clever but false arguments",
     "The argument relied on sophistry rather than logic."),
    ("Spartan",      "adj.", "Showing strict self-discipline; austere",
     "He lived a Spartan lifestyle devoid of luxury."),
    ("Speculate",    "v.",   "To form a theory without firm evidence",
     "Analysts speculated on the company's future."),
    ("Steadfast",    "adj.", "Resolutely or dutifully firm and unwavering",
     "She remained steadfast in her commitment."),
    ("Stigma",       "n.",   "A mark of disgrace associated with a circumstance",
     "The stigma attached to mental illness is decreasing."),
    ("Stolid",       "adj.", "Calm and dependable; not easily moved",
     "His stolid reaction masked inner turmoil."),
    ("Stringent",    "adj.", "Strict, precise, and exacting",
     "The stringent regulations reduced pollution."),
    ("Subdue",       "v.",   "To overcome, quieten, or bring under control",
     "The medication helped subdue the acute symptoms."),
    ("Sublime",      "adj.", "Of great excellence; inspiring awe",
     "The mountain vista was nothing short of sublime."),
    ("Substantiate", "v.",   "To provide evidence to support a claim",
     "She failed to substantiate her accusations."),
    ("Succinct",     "adj.", "Briefly and clearly expressed",
     "His succinct memo conveyed the issue perfectly."),
    ("Supine",       "adj.", "Failing to take action; passive",
     "A supine legislature allowed abuses to continue."),
    ("Surmise",      "v.",   "To suppose something without full evidence",
     "She surmised that the project would be cancelled."),
    ("Surreptitious","adj.", "Kept secret, especially to avoid disapproval",
     "He shot a surreptitious glance at the clock."),
    ("Susceptible",  "adj.", "Likely to be influenced or harmed by something",
     "Young children are especially susceptible to ads."),
    ("Sustain",      "v.",   "To strengthen or support; to keep going",
     "Donations sustained the charity through hard times."),
    ("Sycophancy",   "n.",   "Excessive flattery to gain favor",
     "The culture of sycophancy stifled honest feedback."),
    ("Synthesis",    "n.",   "The combination of elements into a whole",
     "Her thesis offered a masterful synthesis of evidence."),
    ("Tedious",      "adj.", "Too long, slow, or dull; boring",
     "The tedious report lost readers by page two."),
    ("Temperate",    "adj.", "Showing moderation and self-restraint",
     "His temperate reply calmed the heated debate."),
    ("Tenable",      "adj.", "Able to be maintained or defended",
     "The position was no longer tenable after the vote."),
    ("Tenuous",      "adj.", "Very weak or slight; thin",
     "The connection between the two events was tenuous."),
    ("Trepidation",  "n.",   "A feeling of fear or agitation",
     "She approached the stage with some trepidation."),
    ("Tumultuous",   "adj.", "Making an uproar; chaotic",
     "The crowd gave a tumultuous welcome to the team."),
    ("Unassuming",   "adj.", "Not pretentious or arrogant; modest",
     "The unassuming genius preferred solitude to fame."),
    ("Unwitting",    "adj.", "Not aware of the full facts; unintentional",
     "She was an unwitting participant in the scheme."),
    ("Usurp",        "v.",   "To take a position of power illegally",
     "He usurped the chairman's authority gradually."),
    ("Variegated",   "adj.", "Exhibiting different colours or diverse elements",
     "The garden displayed variegated foliage."),
    ("Venial",       "adj.", "Denoting a sin that is not mortal; pardonable",
     "He regarded the lapse as a venial error."),
    ("Verbose",      "adj.", "Using or expressed in more words than needed",
     "The verbose lawyer billed by the hour."),
    ("Visceral",     "adj.", "Relating to deep inward feelings",
     "The speech produced a visceral reaction in the crowd."),
    ("Vivacious",    "adj.", "Attractively lively and animated",
     "Her vivacious personality drew people to her."),
    ("Voluble",      "adj.", "Talking fluently, readily, and at length",
     "The voluble guide explained every detail unprompted."),
    ("Wanton",       "adj.", "Deliberate and unprovoked; gratuitous",
     "The wanton destruction of the artwork caused outrage."),
    ("Winsome",      "adj.", "Attractive or appealing in a fresh, innocent way",
     "Her winsome smile disarmed even harsh critics."),
    ("Wistful",      "adj.", "Having or showing a feeling of vague longing",
     "He cast a wistful look at the old photograph."),
    ("Xenophobia",   "n.",   "Strong dislike or fear of foreigners",
     "The report documented a rise in xenophobia."),
    ("Yeoman",       "n.",   "A person doing hard and useful work",
     "He did yeoman work keeping the project on track."),
]

WORDS = WORDS[:525]   # trim to exactly 525
assert len(WORDS) == 525

MEMORY_TIPS = [
    "Break new words into roots, prefixes, and suffixes to decode meaning instantly.",
    "Write each new word in a sentence about your own life — personal context boosts retention.",
    "Read your new words aloud three times; auditory memory reinforces visual learning.",
    "Group new words by theme or emotion — the brain stores related concepts together.",
    "Before sleep, mentally review today's five words — sleep consolidates memory.",
    "Connect a vivid image to each word; a strange picture is harder to forget.",
    "Use a new word in conversation today — production memory is stronger than recognition.",
    "Teach one of today's words to someone else to deepen your own understanding.",
    "Quiz yourself in reverse: read the definition and recall the word.",
    "Rewrite the example sentence in your own words to make it truly yours.",
]


# ── Helper functions ───────────────────────────────────────────────────────────

def get_words(day, n=5):
    """Return n words for a given 1-based day; safe at boundaries."""
    if day < 1:
        return []
    start = (day - 1) * n
    return list(WORDS[start:start + n])


def blank_sentence(sentence, word):
    """Replace the first case-insensitive occurrence of word with underscores."""
    pattern = re.compile(re.escape(word), re.IGNORECASE)
    return pattern.sub("_" * max(8, len(word)), sentence, count=1)


# ── Styles ─────────────────────────────────────────────────────────────────────

def build_styles():
    base = getSampleStyleSheet()
    S = {}

    def ps(name, font, size, lead, align=TA_LEFT, color=black,
           spacebefore=0, spaceafter=0, left=0):
        S[name] = ParagraphStyle(
            name, parent=base["Normal"],
            fontName=font, fontSize=size, leading=lead,
            alignment=align, textColor=color,
            spaceBefore=spacebefore, spaceAfter=spaceafter,
            leftIndent=left,
        )

    ps("day_header",    "Helvetica-Bold",    13, 16, TA_CENTER, spaceafter=1)
    ps("date_line",     "Helvetica",          8, 10, TA_CENTER, spaceafter=3)
    ps("sec_title",     "Helvetica-Bold",     8.5, 11, spacebefore=3, spaceafter=1)
    ps("word_name",     "Helvetica-Bold",     8.5, 11)
    ps("word_def",      "Helvetica",          8,  10)
    ps("word_example",  "Helvetica-Oblique",  7.5, 10, left=5,
       color=HexColor("#333333"))
    ps("exercise",      "Helvetica",          8,  11)
    ps("tip",           "Helvetica-Oblique",  8,  11, color=HexColor("#444444"))
    ps("box_title",     "Helvetica-Bold",     7.5, 10)
    ps("box_body",      "Helvetica",          7.5, 10)

    return S


# ── Custom dotted-border flowable ──────────────────────────────────────────────

class DottedBox(Flowable):
    """Draws a dotted rectangle and places inline content inside it."""

    def __init__(self, content, width, height, padding=5):
        super().__init__()
        self._content  = content
        self.width     = width
        self.height    = height
        self._padding  = padding

    def wrap(self, aW, aH):
        return self.width, self.height

    def draw(self):
        from reportlab.platypus import Frame
        c = self.canv
        c.saveState()
        c.setDash(2, 3)
        c.setLineWidth(0.5)
        c.rect(0, 0, self.width, self.height, stroke=1, fill=0)
        c.restoreState()
        p = self._padding
        Frame(p, p, self.width - 2*p, self.height - 2*p,
              showBoundary=0).addFromList(list(self._content), c)

    def drawOn(self, canvas, x, y, _sW=0):
        self.canv = canvas
        canvas.saveState()
        canvas.translate(x, y)
        self.draw()
        canvas.restoreState()


# ── Section builders ───────────────────────────────────────────────────────────

def hr():
    return HRFlowable(width="100%", thickness=0.5, color=black,
                      spaceBefore=2, spaceAfter=2)


def section_head(text, S):
    return [hr(), Paragraph(text, S["sec_title"])]


def sec_new(words, S):
    out = section_head("SECTION 1 — NEW ACQUISITIONS", S)
    for i, (word, pos, defn, ex) in enumerate(words):
        out.append(Paragraph(
            f"{word} <font name='Helvetica-Oblique' size='7'>{pos}</font>  "
            f"<font name='Helvetica' size='7.5'>{defn}</font>",
            S["word_name"]))
        out.append(Paragraph(f"<i>{ex}</i>", S["word_example"]))
    return out


def sec_recall(prev, day, S):
    out = section_head("SECTION 2 — 24-HOUR RECALL  (Fill in the Blank)", S)
    if not prev:
        out.append(Paragraph(f"Memory Tip: {MEMORY_TIPS[(day-1) % len(MEMORY_TIPS)]}", S["tip"]))
        return out
    for n, (word, _, _, ex) in enumerate(prev, 1):
        out.append(Paragraph(f"{n}. {blank_sentence(ex, word)}", S["exercise"]))
    return out


def sec_review(rev, day, S, body_w):
    out = section_head("SECTION 3 — 7-DAY DEEP REVIEW  (Match Definition → Word)", S)
    if not rev:
        out.append(Paragraph(f"Memory Tip: {MEMORY_TIPS[(day+2) % len(MEMORY_TIPS)]}", S["tip"]))
        return out
    rng = random.Random(day * 7)
    shuffled = list(rev)
    rng.shuffle(shuffled)
    letters = "ABCDE"
    rows = [["Definition", "Word Bank"]]
    for i, (word, _, defn, _) in enumerate(rev):
        rows.append([
            Paragraph(f"{i+1}. {defn}", S["exercise"]),
            Paragraph(f"{letters[i]}. {shuffled[i][0]}", S["exercise"]),
        ])
    tbl = Table(rows, colWidths=[body_w * 0.60, body_w * 0.40])
    tbl.setStyle(TableStyle([
        ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, 0), 8),
        ("LINEBELOW",     (0, 0), (-1, 0), 0.5, black),
        ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE",      (0, 1), (-1, -1), 8),
        ("VALIGN",        (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING",    (0, 0), (-1, -1), 1),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 1),
        ("LEFTPADDING",   (0, 0), (-1, -1), 2),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 2),
    ]))
    out.append(tbl)
    return out


def sec_mastery(mast, day, S):
    out = section_head("SECTION 4 — 30-DAY ULTIMATE TEST  (Synonym Challenge)", S)
    if not mast:
        out.append(Paragraph(f"Memory Tip: {MEMORY_TIPS[(day+5) % len(MEMORY_TIPS)]}", S["tip"]))
        return out
    for n, (word, _, defn, _) in enumerate(mast, 1):
        clue = next((w for w in defn.split() if len(w) > 4), defn.split()[0])
        out.append(Paragraph(f"{n}. Synonym for '<i>{clue}…</i>'  → ______________",
                             S["exercise"]))
    return out


def personal_box(words, S, width):
    w1 = words[0][0] if words else "Word 1"
    w2 = words[1][0] if len(words) > 1 else "Word 2"
    inner = [
        Paragraph("PERSONAL CONNECTION BOX", S["box_title"]),
        Spacer(1, 2),
        Paragraph(
            f"Write one sentence using both '<b>{w1}</b>' and '<b>{w2}</b>':",
            S["box_body"]),
        Spacer(1, 4),
        Paragraph("_ " * 28, S["box_body"]),
        Spacer(1, 3),
        Paragraph("_ " * 28, S["box_body"]),
    ]
    return DottedBox(inner, width=width, height=54, padding=5)


# ── Day page builder ───────────────────────────────────────────────────────────

def build_day(day, S, body_w):
    day_words  = get_words(day)
    prev_words = get_words(day - 1)
    rev_words  = get_words(day - 7)
    mast_words = get_words(day - 30)

    story = []
    story.append(Paragraph(f"DAY {day}", S["day_header"]))
    story.append(Paragraph("Date: ___________________________", S["date_line"]))
    story.extend(sec_new(day_words, S))
    story.extend(sec_recall(prev_words, day, S))
    story.extend(sec_review(rev_words, day, S, body_w))
    story.extend(sec_mastery(mast_words, day, S))
    story.append(Spacer(1, 2))
    story.append(personal_box(day_words, S, body_w))
    return story


# ── Front-matter helpers ───────────────────────────────────────────────────────

def make_styles_front():
    base = getSampleStyleSheet()
    title  = ParagraphStyle("fm_title",  parent=base["Title"],
                            fontName="Times-Bold",   fontSize=20,
                            leading=26, alignment=TA_CENTER, spaceAfter=10)
    sub    = ParagraphStyle("fm_sub",    parent=base["Normal"],
                            fontName="Times-Roman",  fontSize=12,
                            leading=15, alignment=TA_CENTER, spaceAfter=6)
    body   = ParagraphStyle("fm_body",   parent=base["Normal"],
                            fontName="Helvetica",    fontSize=9,
                            leading=13, spaceAfter=6)
    bhead  = ParagraphStyle("fm_bhead",  parent=base["Normal"],
                            fontName="Helvetica-Bold", fontSize=9,
                            leading=13, spaceAfter=2, spaceBefore=5)
    copy   = ParagraphStyle("fm_copy",   parent=base["Normal"],
                            fontName="Helvetica",    fontSize=8.5,
                            leading=12, alignment=TA_CENTER)
    head2  = ParagraphStyle("fm_head2",  parent=base["Normal"],
                            fontName="Helvetica-Bold", fontSize=12,
                            leading=15, alignment=TA_CENTER, spaceAfter=8)
    return title, sub, body, bhead, copy, head2


# ── Main generator ─────────────────────────────────────────────────────────────

def generate_workbook(filename="Spaced_Repetition_SAT_Workbook.pdf"):
    NUM_DAYS = 105   # 5 front-matter + 105 day pages = 110 pages total

    doc = SimpleDocTemplate(
        filename,
        pagesize=(PAGE_W, PAGE_H),
        leftMargin   = GUTTER,
        rightMargin  = OUTER,
        topMargin    = TOP,
        bottomMargin = BOTTOM,
        title="Advanced SAT/GRE Vocabulary Workbook",
        author="Spaced Repetition System",
    )

    S   = build_styles()
    FM  = make_styles_front()
    title_s, sub_s, body_s, bhead_s, copy_s, head2_s = FM

    story = []

    # ── Page 1: Title ──────────────────────────────────────────────────────
    story += [
        Spacer(1, 1.4 * IN),
        Paragraph("Advanced SAT / GRE", title_s),
        Paragraph("Vocabulary Workbook", title_s),
        Spacer(1, 0.25 * IN),
        Paragraph("A Spaced Repetition System for Lasting Mastery", sub_s),
        Spacer(1, 0.5 * IN),
        Paragraph("525 High-Level Words · 105 Daily Sessions", sub_s),
        Paragraph("New Words · Recall · Review · Mastery", sub_s),
        PageBreak(),
    ]

    # ── Page 2: Copyright ──────────────────────────────────────────────────
    story += [
        Spacer(1, 3.2 * IN),
        Paragraph("© All Rights Reserved", copy_s),
        Spacer(1, 0.1 * IN),
        Paragraph("This workbook may not be reproduced without written permission.", copy_s),
        Spacer(1, 0.2 * IN),
        Paragraph("First Edition · Printed in the United States of America", copy_s),
        PageBreak(),
    ]

    # ── Page 3: Introduction ───────────────────────────────────────────────
    story += [
        Paragraph("Introduction", head2_s),
        Paragraph(
            "Vocabulary is the foundation of every standardized test. This workbook "
            "applies the <i>spacing effect</i> — the cognitive-science finding that "
            "memories are strengthened when reviews are spread across increasing "
            "intervals. Each daily page introduces five new words while recycling words "
            "from 1, 7, and 30 days ago at precisely the moment your brain needs them.",
            body_s),
        Paragraph(
            "Commit to one page per day. The exercises are deliberately varied — "
            "fill-in-the-blank, matching, synonym challenge — to force genuine retrieval "
            "rather than passive recognition.",
            body_s),
        Paragraph(
            "The Personal Connection Box is the single most important exercise. "
            "Creating a sentence from your own life encodes the word in autobiographical "
            "memory, the most durable form of long-term storage.",
            body_s),
        PageBreak(),
    ]

    # ── Page 4: How to Use ─────────────────────────────────────────────────
    story.append(Paragraph("How to Use This Workbook", head2_s))
    steps = [
        ("1. Study New Acquisitions",
         "Read each entry carefully: word, part of speech, definition, and example. "
         "Say the word aloud to engage auditory memory."),
        ("2. Complete the 24-Hour Recall",
         "Without peeking back, fill in the blanks from memory. Struggle is productive."),
        ("3. Work the 7-Day Deep Review",
         "Match definitions to words from seven days ago. If you draw a blank, look the "
         "word up, write it three times, and move on."),
        ("4. Tackle the 30-Day Mastery Test",
         "Produce a synonym for each word. This retrieval practice is the most powerful "
         "predictor of long-term retention."),
        ("5. Write Your Personal Connection",
         "Non-negotiable. One authentic sentence using two new words is worth an hour of "
         "passive re-reading."),
    ]
    for t, d in steps:
        story.append(Paragraph(t, bhead_s))
        story.append(Paragraph(d, body_s))
    story.append(PageBreak())

    # ── Page 5: Word List Reference (Days 1–10, 50 words) ─────────────────
    story.append(Paragraph("Word List Reference — Days 1–7", head2_s))
    ref_rows = [["#", "Word", "PoS", "Definition"]]
    for i in range(35):
        w, pos, defn, _ = WORDS[i]
        ref_rows.append([str(i + 1), w, pos, defn])
    ref_tbl = Table(ref_rows, colWidths=[
        BODY_W * 0.06, BODY_W * 0.18, BODY_W * 0.10, BODY_W * 0.66
    ])
    ref_tbl.setStyle(TableStyle([
        ("FONTNAME",       (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",       (0, 0), (-1, 0), 7.5),
        ("LINEBELOW",      (0, 0), (-1, 0), 0.5, black),
        ("FONTNAME",       (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE",       (0, 1), (-1, -1), 7),
        ("VALIGN",         (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING",     (0, 0), (-1, -1), 1.2),
        ("BOTTOMPADDING",  (0, 0), (-1, -1), 1.2),
        ("LEFTPADDING",    (0, 0), (-1, -1), 2),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [white, HexColor("#F0F0F0")]),
    ]))
    story.append(ref_tbl)
    story.append(PageBreak())

    # ── Day pages ─────────────────────────────────────────────────────────
    for day in range(1, NUM_DAYS + 1):
        story.extend(build_day(day, S, BODY_W))
        story.append(PageBreak())

    # Remove the trailing PageBreak so the PDF ends cleanly
    if isinstance(story[-1], PageBreak):
        story.pop()

    doc.build(story)
    print(f"Generated: {filename}")
    print(f"Total words: {len(WORDS)}")


if __name__ == "__main__":
    generate_workbook()
